name: kssia
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.13+680
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:  ^1.0.3
  modal_bottom_sheet: ^3.0.0
  flutter_rating_bar: ^4.0.0
  intl_phone_field: ^3.2.0
  dotted_border: ^2.1.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http_parser: ^4.0.2
  dropdown_button2: ^2.3.9
  path: ^1.9.0
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  riverpod_annotation: ^2.3.5
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  intl: ^0.18.1
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.0
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.3.2
  socket_io_client: ^3.0.0-beta.2
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  youtube_player_iframe: ^5.1.5
  firebase_messaging: ^15.1.6
  firebase_auth: ^5.1.4
  firebase_core: ^3.4.0
  path_provider: ^2.1.4
  screenshot: ^3.0.0
  mime: ^1.0.6
  animate_do: ^3.3.4
  flutter_local_notifications: ^17.2.3
  flutter_upgrade_version: ^1.1.6
  contact_add: ^0.0.3
  go_router: ^14.2.8
  open_share_plus: ^1.3.0
  pdf: ^3.11.1
  share_plus: ^10.0.2
  searchfield: ^1.1.6
  image_gallery_saver_plus: ^3.0.5
  loading_animation_widget: ^1.3.0
  textfield_search: ^0.11.1
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  flutter_image_compress: ^2.3.0
  flutter_dotenv: ^5.2.1
  minio_flutter: ^0.0.1
  keyboard_avoider: ^0.2.0
  multi_select_flutter: ^4.1.3
  syncfusion_flutter_pdfviewer: ^28.1.39
  app_links: ^6.4.0
  rename_app: ^1.6.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700
  assets:

    - assets/
    - assets/icons/
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path:  "assets/icons/demo_companylogo.png"