name: kssia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:  ^1.0.3
  modal_bottom_sheet: ^3.0.0
  flutter_rating_bar: ^4.0.0
  intl_phone_field: ^3.2.0
  dotted_border: ^2.1.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  font_awesome_flutter: ^10.5.0 

flutter:
  uses-material-design: true
  assets:

    - assets/
    - assets/icons/

   
