name: kssia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:

    - assets\icons\kssiaLogo.png
    - assets\icons\membership_logo.svg
    - assets\icons\posterside_logo.svg
    - assets/icons/lightBulb_feed.png
    - assets\icons\feed_productBag.svg
    - assets/icons/homePage_wepik.png
    - assets\icons\homepage_youtube.png
    - assets\icons\johnkappa_feed.png
    - assets/icons/display_picture_profilePage.png
    - assets/icons/volkwagenLogo.png
    - assets/icons/share_profile_button.png
    - assets/icons/QR_prof.png
    - assets/icons/show_hide_button.png