name: kssia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:  ^1.0.3
  modal_bottom_sheet: ^3.0.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  font_awesome_flutter: ^9.0.0
  font_awesome_flutter: ^10.5.0 

flutter:
  uses-material-design: true
  assets:

    - assets\icons\kssiaLogo.png
    - assets\icons\membership_logo.svg
    - assets\icons\posterside_logo.svg
    - assets\icons\feed_productBag.svg
    - assets\icons\homepage_youtube.png
    - assets\icons\johnkappa_feed.png
    - assets/icons/display_picture_profilePage.png
    - assets/icons/volkwagenLogo.png
    - assets/icons/share_profile_button.png
    - assets/icons/qr_button.png
    - assets/icons/show_hide_button.png
    - assets/icons/QR_card.png
    - assets/icons/expand_button_profile.png
    - assets/icons/feed_active.svg
    - assets/icons/feed_inactive.svg
    - assets/icons/home_active.svg
    - assets/icons/home_inactive.svg
    - assets\icons\profileDp.png
    - assets/icons/people_inactive.svg
    - assets/icons/people_active.svg
    - assets/icons/news_inactive.svg
    - assets/icons/news_active.svg
    - assets/icons/polygon.svg
   
