// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMfXTmc3190afjNkYm6to0MhJ772qTUxY',
    appId: '1:730513867054:android:c8d1a3fade5f0f53777abf',
    messagingSenderId: '730513867054',
    projectId: 'kssia-fcde5',
    databaseURL:
        'https://kssia-fcde5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kssia-fcde5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2xzhxTiagytZENDC4nLOQu8wxpoW4cs8',
    appId: '1:730513867054:ios:1e2a00a3a0ff6d68777abf',
    messagingSenderId: '730513867054',
    projectId: 'kssia-fcde5',
    databaseURL:
        'https://kssia-fcde5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kssia-fcde5.appspot.com',
    iosBundleId: 'com.skybertech.kssia',
  );
}
